### ISSUE TITLE
How to import sunbird into Eclipse?

### ISSUE THREAD

**Issue by mohimoradi** [project-sunbird/sunbird-lms-service#1033]
I wrote an Eclipse plugin and am now collecting a database of large Java Maven projects. I tried to import Sunbird into Eclipse, but it won't let me run the tests.

It displays the following error:

Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project lms-service: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed: A required class was missing while executing org.apache.maven.plugins:maven-site-plugin:3.3:site: org/apache/maven/doxia/siterenderer/DocumentContent

I tried changing the java version or maven version, adding that plugin to maven dependencies, and following all of the StackOverflow suggestions, such as removing the.m2 folder, but none of them worked.

Is Sunbird Eclipse compatible? Is it possible to run their test classes inside Eclipse? If so, what procedure should I follow?

**Comment by amit-tarento** [comment]
@mohimoradi Yes Sunbird is Eclipse compatible. Just import the sunbird as existing maven project in eclipse and run as Right click on project and Run As -> Maven test.

**Comment by mohimoradi** [comment]
Thanks, the problem has been solved by removing the project from the workspace and re-adding it using your instructions.

**Comment by amit-tarento** [comment]
> Thanks, the problem has been solved by removing the project from the workspace and re-adding it using your instructions.

**Comment by amit-tarento** [comment]
> Thanks, the problem has been solved by removing the project from the workspace and re-adding it using your instructions.

@mohimoradi If the issue sorted out? Can you please mark this thread as Answered?
